version: '3'
services:
  mongodb-pagamentos:
    image: mongo
    container_name: pagamentos-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: userdb
      MONGO_INITDB_ROOT_PASSWORD: pass123
    networks:
      - network-challenge

networks:
  network-challenge:
    driver: bridge